version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=1m'
      - '--storage.tsdb.retention.size=100MB'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - monitor_network

  node-exporter:
    image: prom/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    volumes:
      - /:/host:ro,rslave
    deploy:
      mode: global
    ports:
      - "9100:9100"
    labels:
      - "monitoring=true"
    networks:
      - monitor_network


  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    logging:
      driver: "json-file"
      options:
        max-size: "8m"
        max-file: "10"
    networks:
      - monitor_network

 
  traefik:
    image: traefik:v2.10
    command:
      - --providers.docker.swarmmode=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --api.dashboard=true
      - --entrypoints.api.address=:8000
      - --log.level=DEBUG
      - --providers.file.filename=/traefik/dynamic_conf.yml
      - --providers.file.watch=true
    ports:
      - "80:80"
      - "8080:8080"  # Traefik 대시보드
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
    networks:
      - monitor_network


  whoami:
    image: traefik/whoami
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.local`)"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - monitor_network


  metrics-api:
    image: metrics-api:1.0
    working_dir: /app
    volumes:
      - ./metrics-api:/app
    ports:
      - "8000:8000"
    depends_on:
      - prometheus
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - monitor_network

# /etc/hosts에 다음 줄 추가 필요:
# 127.0.0.1 whoami.local

volumes:
   grafana-data: {}

configs:
  prometheus_config:
    file: ./prometheus.yml
  grafana_config:
    file: ./files/grafana.ini

networks:
  monitor_network:
    driver: overlay
    attachable: true
