apiVersion: 1

providers:
  - name: 'Prometheus'
    folder: 'Node Exporter Customize'
    type: file
    disableDeletion: false
    updateIntervalSeconds: 10
    editable: true
    options:
      path: /etc/grafana/provisioning/dashboards

